import {
  AlignCenter,
  AlignLeft,
  AppWindow,
  ArrowDown,
  ArrowLeft,
  ArrowRight,
  ArrowUp,
  AudioLines,
  Bug,
  Camera,
  ChartColumn,
  Check,
  ChevronDown,
  ChevronRight,
  Circle,
  CircleCheck,
  CircleStop,
  CircleX,
  Clapperboard,
  Clock,
  CloudRain,
  Contrast,
  Copy,
  Cpu,
  Download,
  Droplets,
  Ellipsis,
  ExternalLink,
  Eye,
  EyeOff,
  File,
  FileText,
  Folder,
  FolderOpen,
  Gamepad2,
  Gauge,
  Gem,
  Globe,
  Grid3x3,
  Heart,
  Image,
  ImagePlus,
  Info,
  Layers,
  LayoutGrid,
  LifeBuoy,
  ListVideo,
  Lightbulb,
  LoaderCircle,
  Lock,
  Monitor,
  MonitorCog,
  Moon,
  Music,
  Orbit,
  Package,
  PanelBottom,
  Palette,
  Pause,
  Pencil,
  Play,
  Plus,
  Power,
  Puzzle,
  Rainbow,
  Redo2,
  RefreshCw,
  RotateCcw,
  Save,
  ScanEye,
  Search,
  Settings,
  Shuffle,
  SlidersHorizontal,
  Snowflake,
  Sparkles,
  Square,
  Star,
  Store,
  Sun,
  SunMoon,
  ThumbsUp,
  Timer,
  TriangleAlert,
  Trash2,
  Type,
  Undo2,
  Upload,
  Volume2,
  VolumeX,
  WandSparkles,
  Waves,
  Wrench,
  X,
  Zap,
  Flower2,
  type LucideIcon,
} from 'lucide-react';
import type { CSSProperties } from 'react';

const ICONS = {
  'align-center': AlignCenter,
  'align-left': AlignLeft,
  'app-window': AppWindow,
  'arrow-down': ArrowDown,
  'arrow-left': ArrowLeft,
  'arrow-right': ArrowRight,
  'arrow-up': ArrowUp,
  audio: AudioLines,
  bug: Bug,
  camera: Camera,
  chart: ChartColumn,
  check: Check,
  'chevron-down': ChevronDown,
  'chevron-right': ChevronRight,
  circle: Circle,
  'circle-check': CircleCheck,
  'circle-x': CircleX,
  clapperboard: Clapperboard,
  clock: Clock,
  'cloud-rain': CloudRain,
  contrast: Contrast,
  copy: Copy,
  cpu: Cpu,
  download: Download,
  droplets: Droplets,
  external: ExternalLink,
  eye: Eye,
  more: Ellipsis,
  'eye-off': EyeOff,
  file: File,
  'file-text': FileText,
  flower: Flower2,
  folder: Folder,
  'folder-open': FolderOpen,
  gamepad: Gamepad2,
  gauge: Gauge,
  gem: Gem,
  globe: Globe,
  grid: Grid3x3,
  heart: Heart,
  image: Image,
  'image-plus': ImagePlus,
  info: Info,
  layers: Layers,
  playlist: ListVideo,
  'layout-grid': LayoutGrid,
  lifebuoy: LifeBuoy,
  lightbulb: Lightbulb,
  loader: LoaderCircle,
  lock: Lock,
  monitor: Monitor,
  'monitor-cog': MonitorCog,
  moon: Moon,
  music: Music,
  orbit: Orbit,
  package: Package,
  'panel-bottom': PanelBottom,
  palette: Palette,
  pause: Pause,
  pencil: Pencil,
  play: Play,
  plus: Plus,
  power: Power,
  puzzle: Puzzle,
  rainbow: Rainbow,
  redo: Redo2,
  refresh: RefreshCw,
  restore: RotateCcw,
  save: Save,
  'scan-eye': ScanEye,
  search: Search,
  settings: Settings,
  shuffle: Shuffle,
  sliders: SlidersHorizontal,
  snowflake: Snowflake,
  sparkles: Sparkles,
  square: Square,
  star: Star,
  stop: CircleStop,
  store: Store,
  sun: Sun,
  'sun-moon': SunMoon,
  'thumbs-up': ThumbsUp,
  timer: Timer,
  trash: Trash2,
  type: Type,
  undo: Undo2,
  upload: Upload,
  volume: Volume2,
  'volume-off': VolumeX,
  wand: WandSparkles,
  warning: TriangleAlert,
  waves: Waves,
  wrench: Wrench,
  x: X,
  zap: Zap,
} satisfies Record<string, LucideIcon>;

export type IconName = keyof typeof ICONS;

export function Icon({ name, size = 16, className, style, strokeWidth = 1.8 }: { name: IconName; size?: number; className?: string; style?: CSSProperties; strokeWidth?: number }) {
  const Cmp = ICONS[name];
  return <Cmp size={size} strokeWidth={strokeWidth} className={`icon ${className ?? ''}`} style={style} aria-hidden="true" />;
}

export function isIconName(value: string): value is IconName {
  return value in ICONS;
}
